### ISSUE TITLE
cannot use name "global"

### ISSUE THREAD

**Issue by asos-tomp** [eight04/rollup-plugin-external-globals#10]
weirdly, when using:
```
    externalGlobals({
      global: "window"
    }),
```
..I get the error:
> [!] (rollup-plugin-external-globals plugin) SyntaxError: Unexpected token (2:8)

..But any other name for the same, e.g.
```
    externalGlobals({
      foo: "window"
    }),
```
...is fine.

**Comment by eight04** [comment]
Can you upload a working repo that can reproduce the issue?

Note that the first argument is a map of module ID -> variable name. By using `{global: "window"}`, you are asking the plugin to transform all exports of the external module named "global", to a `window` variable.
