### ISSUE TITLE
Export xxx is not defined when with commonjs

### ISSUE THREAD

**Issue by chengcyber** [eight04/rollup-plugin-external-globals#19]
`@rollup/plugin-commonjs` will create a virtual module like `foo?commonjs-external`

Assuming the source code is `export { default } from 'foo'`, and the external-globals setting is `{ foo: "FOO" }`

thus, the output is `export { FOO as default };`. Here, rollup complains `Export 'FOO' is not defined` from the code of [this line](https://github.com/acornjs/acorn/blob/47a5affad78e4b53a3e22d07ddbb220eed1f3d76/acorn/src/statement.js#L27)

Could we add a line for `FOO` when handling export? such as:

```
const FOO = globalThis.FOO;
export { FOO as default };
```

**Comment by eight04** [comment]
Never thought that this can be hit by commonjs plugin. I guess we have to fix this:
https://github.com/eight04/rollup-plugin-external-globals/blob/d019ba7aff13eb536192eebab23f840e6200d614/test/test.js#L301-L316

**Comment by chengcyber** [comment]
Hi @eight04, I tend to solve this issue by https://github.com/eight04/rollup-plugin-external-globals/pull/20 . Could you kindly take a look?
