### ISSUE TITLE
How to delete CSS import

### ISSUE THREAD

**Issue by lihanspace** [eight04/rollup-plugin-external-globals#24]
My code

```js
import MdEditorV3 from 'md-editor-v3'
import 'md-editor-v3/lib/style.css'
```

Now I can convert the JS import into a global variable, but my CSS import is still there. Maybe a new feature can be created to delete this import.

```js
externalGlobals({
  'md-editor-v3': 'mdEditorV3',
  'md-editor-v3/lib/style.css': ''
})
```

I don't know if there are any plugins with similar features now

**Comment by lihanspace** [comment]
Or you can delete not just CSS imports, but any imports

**Comment by eight04** [comment]
May I ask the reason for adding CSS import to the code?

**Comment by lihanspace** [comment]
I use vite to build vue3.0 applications, and vite uses rollup. The components I use in Vue applications need to be imported into CSS.

**Comment by eight04** [comment]
So there is a component using `md-editor-v3` and you want to include the component in the bundle without including `md-editor-v3`?

Can you test if this works?
```js
externalGlobals({
  'md-editor-v3/lib/style.css': 'foo'
})
```

I think there are two issues here:

1. Make the plugin be able to work with bare imports.
2. We should warn the user when a module is marked as external (`md-editor-v3`) but its sub-module is not (`md-editor-v3/lib/style.css`)

**Comment by lihanspace** [comment]
Sorry, I'm busy today. I'll test this tomorrow.

I only import md-editor-v3 in the development environment. In the production environment, I use md-editor-v3 through script tag and link tag. 

The feature of injecting tags is provided by vite. I think rollup-plugin should have the feature of deleting imports and complete the second issue you mentioned. 

However, I don't think it is necessary to make the plugin be able to work with bare import，otherwise the plugin will be too complex.

**Comment by lihanspace** [comment]
Well, this works is OK. It successfully deleted my CSS import.
