### ISSUE TITLE
Plugin ordering rollup-plugin-commonjs

### ISSUE THREAD

**Issue by brendon** [eight04/rollup-plugin-external-globals#27]
Hi there, in the docs you mention:

> Note: this plugin only works with import/export syntax. If you are using a module loader transformer e.g. rollup-plugin-commonjs, you have to put this plugin after the transformer plugin.

I'm trying to use this plugin from Vite. My config is:

```
export default defineConfig({
  plugins: [
    RubyPlugin()
  ],
  server: {
    hmr: {
      host: 'vitedevserver.test',
      clientPort: 443
    }
  },
  build: {
    rollupOptions: {
      plugins: [externalGlobals({ jquery: "$" })]
    }
  }
})
```

But jQuery still gets imported via something like: `import{r as ne}from"./jquery.a40d0dc7.js"`

I was wondering if you knew how to ensure the commonjs plugin runs first per the comment above?

**Comment by eight04** [comment]
I'm not familiar with vite. Could you provide a full repro?

**Comment by brendon** [comment]
I'll have a look at that tomorrow :) Behind the scenes Vite just uses `@rollup/plugin-commonjs`.

**Comment by brendon** [comment]
My solution ended up being a Vite plugin:

```
import { defineConfig } from 'vite'
import RubyPlugin from 'vite-plugin-ruby'
import { globalExternals } from '@fal-works/esbuild-plugin-global-externals'

function WindowJquery() {
  const virtualModuleId = 'jquery'
  const resolvedVirtualModuleId = '\0' + virtualModuleId

  return {
    name: 'window-jquery',
    resolveId(id) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId
      }
    },
    load(id) {
      if (id === resolvedVirtualModuleId) {
        return `export default window.jQuery`
      }
    }
  }
}

export default defineConfig({
  plugins: [
    RubyPlugin(),
    {
      ...WindowJquery(),
      enforce: 'pre'
    }
  ],
  server: {
    hmr: {
      host: 'vitedevserver.test',
      clientPort: 443
    }
  },
  optimizeDeps: {
    esbuildOptions: {
      plugins: [globalExternals({ jquery: { type: "cjs", varName: "$" } })]
    }
  }
})
```

The esbuild plugin is required too since Vite uses esbuild in development mode! 🥺

**Comment by porfirioribeiro** [comment]
I know this issue is closed, but some people may search for the same problem, like me.
I found out how to fix this with Vite, you need to ensure the order to be `enforce: 'post'`
The plugin does not have it, as it is something that Vite built on top of Rollup: https://vitejs.dev/guide/using-plugins.html#enforcing-plugin-ordering

I have this litle wrapper plugin to make this plugin works with Vite:
```ts
import { Plugin } from 'vite';
import externalGlobals from 'rollup-plugin-external-globals';

/**
 * Vite Plugin to replace imports with global variables. Works with ESM
 */
export function globals(map: Record<string, string>): Plugin[] {
  return [
    {
      name: 'globals',
      configResolved(config) {
        config.optimizeDeps.exclude = (config.optimizeDeps.exclude ?? []).concat(Object.keys(map));
      },
    },
    {
      ...externalGlobals(map),
      enforce: 'post',
    } as Plugin,
  ];
}
```

Can be used like this:

```ts
  globals({
    vue: 'Vue',
  }),
```

Hope this can help someone

**Comment by brendon** [comment]
Lol, thanks @porfirioribeiro, not sure why I didn't try that. To be fair I was fairly green with Vite at the time.

**Comment by brendon** [comment]
In the end I actually switched to using `esbuild` mode for Vite in production so I didn't need my custom plugin and just used `@fal-works/esbuild-plugin-global-externals`. That's the default for Vite 4 I think. I never really understood why the dev and production had different build environments. It caused me a lot of confusion and bugs.

**Comment by porfirioribeiro** [comment]
> Lol, thanks @porfirioribeiro, not sure why I didn't try that. To be fair I was fairly green with Vite at the time.

I get that, I spend a couple of hours myself to find out how to make it work. Even used your suggestion on this issue 👍
