### ISSUE TITLE
Unmet peer dependency with Vite v5 

### ISSUE THREAD

**Issue by NPanayotov** [eight04/rollup-plugin-external-globals#38]
> warning " > rollup-plugin-external-globals@0.9.2" has unmet peer dependency "rollup@^2.25.0 || ^3.3.0 || ^4.1.4".

**Comment by eight04** [comment]
Have you installed rollup? Try running this command:
```
npm ls rollup
```

**Comment by NPanayotov** [comment]
Seems to be fixed now. Thank you.
