### ISSUE TITLE
Vite build crashes when the main entry is an HTML file

### ISSUE THREAD

**Issue by Kirill-Cherepanov** [eight04/rollup-plugin-external-globals#40]
![image](https://github.com/eight04/rollup-plugin-external-globals/assets/52123816/10f96116-ddc9-4ccc-952f-751282344299)

A basic project made with create vite react and rollup-plugin-external-globals added on top:
https://github.com/Kirill-Cherepanov/-rollup-plugin-external-globals-crash

If I understood correctly, it tries to parse the html entry as a js file.

**Comment by eight04** [comment]
We should catch and suppress parsing error:
https://github.com/eight04/rollup-plugin-external-globals/blob/73675699bf35e68945bf319c401acedaff98a888/index.js#L37
