### ISSUE TITLE
wrong rollup version in peerDependencies 

### ISSUE THREAD

**Issue by chouchouji** [eight04/rollup-plugin-external-globals#51]
# Problem

I found an error caused by this plugin while building my vue project.

![image](https://github.com/user-attachments/assets/9cdb3b2e-cdd8-4cba-afae-467c7fa43866)

# Solution

I cloned the 2.79.1 rollup source code. There are no any debug api.

![image](https://github.com/user-attachments/assets/8395e064-0d1c-4cd3-aa97-413960fe9458)

In the official changelog. `The debug ` api was supported first in `3.25.0` version

![image](https://github.com/user-attachments/assets/544af694-78b6-4d00-8103-809b74805921)

If you think it is peerDependencies error, I am pleased to submit a pr to fix it. 

# Environment

vite: 3.2.8
rollup-plugin-external-globals: 0.12.0

**Comment by eight04** [comment]
Does it work with rollup 2 by removing the debug statement?

**Comment by chouchouji** [comment]
> Does it work with rollup 2 by removing the debug statement?

Yes. I changed it to `this.warning`. It worked well. I can see the warning in the terminal.

**Comment by chouchouji** [comment]
So, how about changing `this.debug` to  other api like `this.warning`? It is very helpful to adapt to more rollup versions.
