### ISSUE TITLE
The plugin doesn't process virtual modules

### ISSUE THREAD

**Issue by dkumor** [eight04/rollup-plugin-external-globals#6]
Hi! The plugin looks like exactly what I was looking for, but I have not been able to make it work when embedding external modules. I have the following rollup config:

```es
import resolve from "rollup-plugin-node-resolve";
import commonjs from "rollup-plugin-commonjs";
import externalGlobals from "rollup-plugin-external-globals";

export default {
  input: "test.js",
  output: {
    name: "test",
    file: "test.jsm",
    format: "es"
  },
  plugins: [
    externalGlobals({
      vue: "Vue"
    }),
    resolve(),
    commonjs()
  ]
};
```

the file `test.js` is the following:
```es
import Vue from "vue";
import Vuetify from "vuetify";
Vue.use(Vuetify);
```

I was expecting the plugin to replace imports of 'vue' to the global variable Vue, however, the following happens:
- If I do not have vue listed as external, it is embedded in the bundle
- If I do have it listed as external, the generated file,`test.jsm` has an import at the very top: `import vue from 'vue'`. If I manually replace the import in the generated bundle with `const vue = Vue;`, the resulting bundle works without issue.
- If I have it listed as external, but do not include the plugin, the import in the bundle changes to `import Vue from 'vue';`, so the plugin is doing something there...
- The order of the plugins makes no difference
- If I remove the `import Vue from "vue"` in test.js, the generated file still includes the import (vuetify also imports it)

Note that the plugin works when just importing local code, to the best of my knowledge (it worked when I removed the 'Vuetify' import).

I am unsure why exactly this is happening - my guess is that the commonjs code is processed differently, but I am not sure if that's the issue - it might be something entirely different.

**Comment by eight04** [comment]
I guess the problem is that we don't transform proxy modules generated by CommonJS plugin. Try finding the plugin (`node_modules/rollup-plugin-external-globals/index.js`) and changing this line from
https://github.com/eight04/rollup-plugin-external-globals/blob/c5f37af94f9c5a1fc7fee6deca3db6bbb179bdce/index.js#L14
to
```js
if (id[0] !== "\0" && !filter(id)) {
  return;
}
```

**Comment by dkumor** [comment]
With the given modification, the output's header changes to:
```
import 'vue';
```

**Comment by dkumor** [comment]
I have included a minimal environment necessary to reproduce this here (two files above+ minimal package.json):
[testenv.zip](https://github.com/eight04/rollup-plugin-external-globals/files/2923207/testenv.zip)

running:
```
npm i
npm run build
```

produces test.jsm with the above issues

**Comment by eight04** [comment]
You have to use CommonJS plugin before this one.

**Comment by dkumor** [comment]
It works! Thank you so much!

**Comment by dkumor** [comment]
Would it be possible to get a release published with the above fix?

**Comment by eight04** [comment]
The only problem is that I'm not sure if we should transform all virtual modules ignoring the `exclude`/`include` option. Technically, the transformation should apply to all files including virtual modules, or there will be an untransformed import left in the bundle.

These options might be able to speed up the build though (e.g. excluding large files).

I will push a minor release that transforms all virtual modules. If it breaks something then I guess we will have to fix https://github.com/rollup/rollup-pluginutils/issues/54.

**Comment by dkumor** [comment]
Thanks a lot!
